version: '3.9'

services:
  mercor-backend:
    platform: linux/arm64
    container_name: mercor-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=DEV
      - DEBUG=true
      - DOC_URL=/docs

      # Server Configurations
      - HOST=0.0.0.0
      - PORT=8080

      # MongoDB Configurations
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=mercor_dev
      - MONGO_USERNAME=mercor_user
      - MONGO_PASSWORD=mercor_password
      - MONGO_URI_FORMAT=mongodb://{}:{}@{}:{}

      # Security Configuration
      - SECRET_KEY=mf00lxCoYX7CMpBySXPxMS+wt7H2lEkyqjNxtX8rCuk=

    ports:
      - "8080:8080"
    volumes:
      - .:/mercor-backend
    depends_on:
      - mongodb
    networks:
      - mercor-network
    restart: unless-stopped

  mongodb:
    container_name: mercor-mongodb
    platform: linux/arm64
    image: mongo:7.0
    environment:
      - MONGO_INITDB_DATABASE=mercor_dev
      - MONGO_INITDB_ROOT_USERNAME=mercor_user
      - MONGO_INITDB_ROOT_PASSWORD=mercor_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mercor-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  mercor-network:
    driver: bridge
